#!/usr/bin/env bash

if command -v npm &>/dev/null; then
  npm config set sign-git-tag true
fi

git config --global gpg.format ssh
git config --global commit.gpgSign true
git config --global user.email "development.team@dosyago.com"
git config --global user.name "DOSAYGO Engineering"
git config --global core.editor "vim"
git config --global pull.rebase false
git config --global init.defaultBranch boss
git config --global user.signingKey "$HOME/.ssh/id_ed25519.pub"
git config --global gpg.ssh.allowedSignersFile ~/.config/git/allowed_signers
git config --global core.hooksPath ~/.config/git/hooks

mkdir -p ~/.config/git/
touch ~/.config/git/allowed_signers
mkdir -p ~/.config/git/hooks/
cp scripts/no-large-files.sh ~/.config/git/hooks/pre-commit
chmod -R +x ~/.config/git/hooks/*

echo "development.team@dosyago.com $(cat ~/.ssh/id_ed25519.pub)" >> ~/.config/git/allowed_signers

sudo cp commands/* /usr/local/bin

cp bashrc $HOME/.bashrc.new
cp vimrc $HOME/.vimrc
sudo cp vimrc /root/.vimrc
sudo cp bashrc /root/.bashrc.new
echo ".bashrc is in .bashrc.new -> manually copy if you want to use it" >&2

cp .bash_aliases $HOME/.bash_aliases
mkdir -p ~/.config/nvim
cp init.lua ~/.config/nvim

sudo mkdir -p /usr/share/games/cfortunes/
sudo cp cfortunes/* /usr/share/games/cfortunes/

if command -v apt &>/dev/null; then
  sudo apt -y install pandoc iptables moreutils
elif command -v pkg &>/dev/null; then
  sudo pkg install -y pandoc iptables moreutils
elif command -v dnf &>/dev/null; then
  sudo dnf install -y pandoc iptables moreutils
elif command -v yum &>/dev/null; then
  sudo yum install -y pandoc iptables moreutils
fi

cp .bash_aliases $HOME/.bash_aliases
cp scripts/renew_tls.sh $HOME/.renew_tls.sh

if [[ "$OSTYPE" == darwin* ]]; then
  sudo cp macos-commands/* /usr/local/bin/
fi
